### ISSUE TITLE
Command Arguments

### ISSUE THREAD

**Issue by laktak** [lambdan/imageviewer5#8]
Would it be possible to add additional arguments so that the app can be controlled from the commandline? I'd like to use your app in combination with ranger (a commandline file manager).

For example `open -a /Applications/imageviewer5.app "path-to-file.heic"` opens the image in the app but if the application has not been launched the window is very tiny.

PS: thank you for making this, the HEIC display is really fast!

**Comment by laktak** [comment]
I had a few ideas that would probably not fit into your app. I'll put it on GitHub if you are interested. In any case thank you for the starting point!

**Comment by lambdan** [comment]
Sorry, didn't see this until now. 

I'm actually surprised that opening from the command line works at all because I don't remember implementing that, but I guess I got that for free with one of the other methods I implemented :)

Yeah the tiny window thing is annoying and always has been annoying. Everytime I use the app myself I am annoyed by it. 

So I went ahead and tried to fix it! Window size is now remembered from last run, so it's better atleast. I also specified some idealWidth and idealHeight flags to be the image dimensions, but that doesn't seem to do anything. I also set the max window size to be your display resolution.

Give it a try: https://github.com/lambdan/imageviewer5/releases/tag/1.3

**Comment by laktak** [comment]
Looks good! Not sure if you have ever looked at macOS QuickView (launched by `space` from Finder) - it can display almost everything but for some reason takes forever to load HEIC images. At first I thought you were using a special library to load the images so quickly - I'm still surprised that it's just the standard SwiftUI controls.

**Comment by lambdan** [comment]
Yes I wanted to just QuickView or Preview or whatever its called so I didn't have to do all this, but I absolutely cannot stand how you navigate through images in it. Like if your Finder window is in list view, you navigate by pressing Up and Down. If you have Icons you have to left/right and then down/up. Basically you navigate the Finder window, you don't navigate anything in the QuickView, and I hate that.
